"""
Decision_Maker_Machine.py  (gantt-loader version)

Strips out the entire previous (ta01) structure; its only role now is to load the
planned_gantt.csv pre-generated by gen_machine.py and feed it to the simulation.

Removed:
  - JSSPData (ta01 parser)
  - All SchedulingAlgorithm (SPT/FIFO/MWKR/External) — schedule "generation"
    is now handled by gen_machine.py (ECT + machine travel + CONWIP)
  - ATC/composite dispatch rule, plan_ref, machine_plan_order
  - CSVExporter's gantt/from_to/initial generation (gen_machine.py already generates them)

Retained connections (called as-is by Simulation_Main):
  - MachineDecisionMaker(jssp_cfg)            constructor
  - .run_scheduling(transport_func=...)       gantt load (not schedule "generation")
  - .choose_next_job(station)                 min planned_ready among in_buffer (replay plan order)
  - .schedule                                 GanttSchedule instance
  - .makespan                                 gantt planned makespan
  - get_active_machine_decision()             global accessor
  - GanttHTMLExporter                         result CSV -> HTML (preserved, ta01-independent)

Attributes read from config (JSSPConfig) (defaults if absent):
  - planned_gantt_csv : input gantt path (gen_machine.py output)
  - step_info_path    : ProcessStepInfo.txt (for realized proc sampling)
  - pt_scale          : same scale as when gantt was generated
"""
from __future__ import annotations

import csv
import os
from collections import defaultdict
from typing import Any, Callable, Optional

from Simulation_Machine_Config import JSSPConfig
from Gantt_Schedule import GanttSchedule


ACTIVE_MACHINE_DECISION = None


def get_active_machine_decision():
    return ACTIVE_MACHINE_DECISION


# ══════════════════════════════════════════════════════════════════════
# MachineDecisionMaker — gantt loader + plan-order dispatch
# ══════════════════════════════════════════════════════════════════════

class MachineDecisionMaker:
    """
    Role 1 — before simulation start (run_scheduling):
        Load the planned_gantt.csv produced by gen_machine.py as a GanttSchedule.
        (Does not "generate" a schedule. Reads an already-built plan.)

    Role 2 — during simulation (choose_next_job):
        Among the lots that have arrived at the machine in_buffer, pick the one with
        the earliest planned_ready (= gantt planned end time, i.e. planned processing
        order) -> replays the gantt plan order. Because congestion may cause a lot
        other than the planned one to arrive first, take the min "among those arrived".
    """

    def __init__(self, jssp_cfg: JSSPConfig = None, algorithm=None):
        global ACTIVE_MACHINE_DECISION
        self.jssp_cfg = jssp_cfg or JSSPConfig()

        # input path (default if absent in config)
        self.planned_gantt_csv = getattr(
            self.jssp_cfg, "planned_gantt_csv", "gantt_final/planned_gantt.csv")
        self.step_info_path = getattr(
            self.jssp_cfg, "step_info_path", "ProcessStepInfo.txt")
        self.pt_scale = float(getattr(self.jssp_cfg, "pt_scale", 0.75))

        # GanttSchedule = the routing/timing source consumed by the simulation
        self.schedule: Optional[GanttSchedule] = None
        # backward-compat alias. (Main's .jssp_data references to be replaced with schedule later)
        self.jssp_data = None
        self.makespan: float = 0.0

        ACTIVE_MACHINE_DECISION = self

        # load immediately in __init__ (no layout needed — gantt is an already-complete file)
        if os.path.exists(self.planned_gantt_csv):
            self._load_gantt()
        else:
            print(f"[MachineDecisionMaker] planned_gantt.csv not found: "
                  f"{self.planned_gantt_csv} (retry in run_scheduling)")

    # ------------------------------------------------------------------
    def _load_gantt(self):
        self.schedule = GanttSchedule(
            gantt_csv=self.planned_gantt_csv,
            step_info_csv=self.step_info_path if os.path.exists(self.step_info_path) else None,
            pt_scale=self.pt_scale,
        )
        self.jssp_data = self.schedule  # backward-compat alias
        # planned makespan = max planned_end over all ops
        # + for strict plan-order execution: per-machine op sequence (in planned_start order)
        mk = 0.0
        seq = defaultdict(list)
        for r in self.schedule.routes.values():
            for op in r.ops:
                if op.planned_end > mk:
                    mk = op.planned_end
                seq[op.machine].append((op.planned_start, op.lot_id, int(op.step_no)))
        self.makespan = mk
        self._machine_seq = {m: sorted(v) for m, v in seq.items()}   # m_name -> [(start, lot, step)]
        self._machine_ptr = {m: 0 for m in self._machine_seq}        # index of next plan op to process

    # ------------------------------------------------------------------
    # Role 1: gantt load (not schedule generation). Signature preserved to keep the connection.
    # transport_func / transport_resolver are already reflected in the gantt, so ignored.
    # ------------------------------------------------------------------
    def run_scheduling(self,
                       transport_func: Optional[Callable[[int, int], float]] = None,
                       transport_resolver: Optional[Callable[..., Any]] = None):
        print("\n[MachineDecisionMaker] ── gantt load ──")
        if self.schedule is None:
            if not os.path.exists(self.planned_gantt_csv):
                print(f"  planned_gantt.csv not found: {self.planned_gantt_csv}")
                return
            self._load_gantt()
        n_lots = len(self.schedule.lot_ids())
        n_mach = len(self.schedule.machines())
        n_ops = sum(len(r.ops) for r in self.schedule.routes.values())
        print(f"  file   : {self.planned_gantt_csv}")
        print(f"  content: {n_lots} lots × {n_mach} machines, {n_ops} ops")
        print(f"  realized proc distribution: {'ON' if self.schedule.step_dist else 'OFF (=planned)'}")
        print(f"  planned makespan: {self.makespan:,.0f}s = {self.makespan/3600:.2f}hr")
        print("[MachineDecisionMaker] ── done ──\n")

    # ------------------------------------------------------------------
    # Role 2: plan-order dispatch — min planned_ready among in_buffer arrivals
    # ------------------------------------------------------------------
    def choose_next_job(self, machine_station):
        if not machine_station.in_buffer:
            return None

        # strict plan-order: the machine processes ops exactly in the planned order.
        # If the lot for the next planned op has not arrived yet, return None -> machine *waits* (idle).
        # (does not process another arrived lot first -> realized is a clean right-shift of the plan)
        strict = bool(getattr(self.jssp_cfg, "machine_strict_plan_order", True))
        m_name = getattr(machine_station, "machine_name", None)
        seq = getattr(self, "_machine_seq", {}).get(m_name) if (strict and m_name) else None
        if seq is not None:
            ptr = self._machine_ptr.get(m_name, 0)
            if ptr >= len(seq):
                return None
            _, plot, pstep = seq[ptr]
            for job in machine_station.in_buffer:
                if (getattr(job, "lot_id", "") == plot
                        and int(getattr(job, "step_no", -1)) == pstep):
                    self._machine_ptr[m_name] = ptr + 1
                    return job
            return None   # next planned lot has not arrived yet -> wait

        # work-conserving fallback (strict off / no seq): min planned_ready among arrivals
        sched = self.schedule

        def key(job):
            pr = None
            if sched is not None:
                pr = sched.planned_ready(getattr(job, "lot_id", ""),
                                         getattr(job, "step_no", 0))
            return (pr if pr is not None else float("inf"),
                    job.created_time, job.job_id)

        return min(machine_station.in_buffer, key=key)

    # ------------------------------------------------------------------
    # backward-compat: when some code asks for plan info (empty dict if absent)
    # ------------------------------------------------------------------
    def get_plan_info(self, lot_id: str, step_no: int) -> dict:
        if self.schedule is None:
            return {}
        op = self.schedule.op(lot_id, step_no)
        if op is None:
            return {}
        return {
            "planned_start": op.planned_start,
            "planned_end": op.planned_end,
            "machine": op.machine,
            "process_time": op.planned_proc,
        }


# ══════════════════════════════════════════════════════════════════════
# E. GanttHTMLExporter
# ══════════════════════════════════════════════════════════════════════

class GanttHTMLExporter:
    """Two-tier bar gantt showing processing and transport separately, for both planned and actual."""

    JOB_COLORS = [
        "#4E79A7", "#F28E2B", "#E15759", "#76B7B2", "#59A14F",
        "#EDC948", "#B07AA1", "#FF9DA7", "#9C755F", "#BAB0AC",
        "#3D405B", "#81B29A", "#F2CC8F", "#E07A5F", "#264653",
    ]
    TRANSPORT_COLOR = "#8b949e"

    def __init__(self, jssp_cfg: JSSPConfig):
        self.cfg = jssp_cfg
        self.window = int(jssp_cfg.window_sec)
        self.transport_len = 0.0

    def _fmt(self, sec):
        s = max(0, int(float(sec)))
        h, r = divmod(s, 3600)
        m, s = divmod(r, 60)
        return f"{h:02d}:{m:02d}:{s:02d}"

    def _pct(self, v):
        return f"{(float(v) / self.window * 100) if self.window else 0.0:.3f}%"

    def _read_csv(self, path):
        if not os.path.exists(path):
            return []
        with open(path, newline='', encoding='utf-8') as f:
            return list(csv.DictReader(f))

    def _bar_html(self, left, width, color, label, title, extra_class=""):
        if width <= 0:
            return ""
        cls = f"bar {extra_class}".strip()
        safe_label = label if width > 1.2 else ""
        return (
            f'<div class="{cls}" style="left:{left:.3f}%;width:{width:.3f}%;background:{color}" '
            f'title="{title}"><span class="bl">{safe_label}</span></div>\n'
        )

    @staticmethod
    def _digits(s):
        return ''.join(c for c in str(s) if c.isdigit())

    def _m_int(self, s):
        """'M7'/'7'/'M07' -> 7 (machine number). -1 on failure."""
        d = self._digits(s)
        return int(d) if d else -1

    def _lot_int(self, s):
        """'L0057' -> 57 (integer for color/identification). 0 on failure."""
        d = self._digits(s)
        return int(d) if d else 0

    def _build_planned_rows(self, planned_rows):
        """planned_gantt.csv -> planned rows per machine (only ops within window)."""
        rows_by_machine = defaultdict(list)
        job_comp = {}
        for r in planned_rows:
            try:
                machine_id = self._m_int(r.get('machine'))
                lot = r.get('lot_id', '')
                lot_i = self._lot_int(lot)
                step = int(float(r.get('step_no') or 0))
                st = float(r['start_sec'])
                et = float(r['end_sec'])
                proc = float(r.get('planned_proc_sec') or (et - st))
                ready = float(r.get('ready_at_machine_sec') or st)
                ptravel = float(r.get('planned_travel_sec') or 0.0)
            except Exception:
                continue
            if machine_id < 0:
                continue
            if self.window and st > self.window:   # skip plans outside window (limit to comparable range)
                continue
            trans_start = max(0.0, ready - ptravel)   # planned transport into this step (just before arrival)
            job_comp[lot_i] = max(job_comp.get(lot_i, 0.0), et)
            rows_by_machine[machine_id].append({
                'machine_id': machine_id, 'job_id': lot_i, 'lot_id': lot, 'op_index': step,
                'start': st, 'end': et, 'visual_end': et, 'proc': proc,
                'trans': ptravel, 'trans_start': trans_start,
            })
        return rows_by_machine, job_comp

    def _build_actual_rows(self, sim_rows, tmap):
        """log_machine_sim.csv (+ transport.csv join) -> actual rows per machine."""
        rows_by_machine = defaultdict(list)
        job_comp = {}
        for r in sim_rows:
            try:
                machine_id = self._m_int(r.get('machine_no') or r.get('machine_name'))
                lot = r.get('lot_id', '')
                lot_i = self._lot_int(lot)
                step = int(float(r.get('step_no') or 0))
                st = float(r['start_time'])
                et = float(r['end_time'])
                proc = max(0.0, float(r.get('process_time') or (et - st)))
                ready_dev = float(r.get('ready_deviation') or 0.0)
            except Exception:
                continue
            if machine_id < 0:
                continue
            # join actual transport into this step (transport.csv) -> transport bar just before arrival
            trans = 0.0
            trans_start = st
            tr = tmap.get((lot, step))
            if tr:
                try:
                    le = float(tr.get('load_end_time') or 0.0)
                    ue = float(tr.get('unload_end_time') or tr.get('dropoff_time') or 0.0)
                    if le > 0.0 and ue > le:
                        trans = ue - le
                        trans_start = le
                except Exception:
                    pass
            job_comp[lot_i] = max(job_comp.get(lot_i, 0.0), et)
            rows_by_machine[machine_id].append({
                'machine_id': machine_id, 'job_id': lot_i, 'lot_id': lot, 'op_index': step,
                'start': st, 'end': et, 'visual_end': et, 'proc': proc,
                'trans': trans, 'trans_start': trans_start, 'ready_dev': ready_dev,
            })
        return rows_by_machine, job_comp

    def _render_machine_rows(self, rows_by_machine, machine_ids, mode='planned'):
        """Machine row = processing (machine occupancy) only. Transport is a rail/OHT resource,
        so it is not drawn on the machine row. Gaps between bars = machine idle/starvation
        (transport delay / waiting). Planned is packed with no gaps; actual develops gaps
        equal to the transport delay, exposing starvation."""
        html_rows = ""
        max_end = 0.0
        scale = float(getattr(self, "_axis", 0.0) or self.window or 1.0)
        for machine_id in machine_ids:
            bars = ""
            entries = sorted(rows_by_machine.get(machine_id, []), key=lambda x: x['start'])
            for r in entries:
                max_end = max(max_end, r.get('visual_end', r.get('end', 0.0)))
                lot_i = r['job_id']
                col = self.JOB_COLORS[(lot_i - 1) % len(self.JOB_COLORS)] if lot_i > 0 else self.JOB_COLORS[0]
                proc_left = r['start'] / scale * 100
                proc_width = r['proc'] / scale * 100
                lab = r.get('lot_id', '')
                tag = 'Planned' if mode == 'planned' else 'Actual'
                proc_tip = (
                    f"[{tag}] {lab} / step {r['op_index']} → M{machine_id:02d}&#10;"
                    f"Start:{self._fmt(r['start'])}  End:{self._fmt(r['end'])}&#10;"
                    f"Proc:{r['proc']:.0f}s"
                )
                if mode == 'actual':
                    proc_tip += f"  ready_dev:{r.get('ready_dev', 0.0):+.0f}s"
                bars += self._bar_html(proc_left, proc_width, col, '', proc_tip, 'proc-bar')

            html_rows += (
                f'<div class="g-row"><div class="g-lbl">M{machine_id:02d}</div>'
                f'<div class="g-track">{bars}</div></div>\n'
            )
        return html_rows, max_end

    def export(self) -> str:
        planned_path = getattr(self.cfg, "planned_gantt_csv", "")
        if not planned_path or not os.path.exists(planned_path):
            print(f"[GanttHTMLExporter] planned_gantt.csv not found -> skip: {planned_path}")
            return ""

        planned = self._read_csv(planned_path)
        sim_rows = self._read_csv(self.cfg.log_machine_csv.replace('.csv', '_sim.csv'))
        out_dir = os.path.dirname(os.path.abspath(self.cfg.log_oht_csv)) or '.'
        transport = self._read_csv(os.path.join(out_dir, 'transport.csv'))
        oht = self._read_csv(self.cfg.log_oht_csv)

        # index transport.csv by (lot_id, step_no) -> for joining actual arrival transport bars
        tmap = {}
        for tr in transport:
            try:
                tmap[(tr.get('lot_id', ''), int(float(tr.get('step_no') or -1)))] = tr
            except Exception:
                continue

        planned_by_m, planned_job_comp = self._build_planned_rows(planned)
        actual_by_m, actual_job_comp = self._build_actual_rows(sim_rows, tmap)

        machine_ids = sorted(set(planned_by_m.keys()) | set(actual_by_m.keys()))
        n_m = len(machine_ids)
        n_j = len({self._lot_int(r.get('lot_id', '')) for r in sim_rows}) if sim_rows else 0

        planned_makespan = max((r['visual_end'] for rows in planned_by_m.values() for r in rows), default=0.0)
        actual_makespan = max((r['visual_end'] for rows in actual_by_m.values() for r in rows), default=0.0)
        axis_makespan = max(planned_makespan, actual_makespan, float(self.window))
        self._axis = axis_makespan   # same scale for bars/ticks

        planned_total = sum(r['proc'] for rows in planned_by_m.values() for r in rows)
        actual_total = sum(r['proc'] for rows in actual_by_m.values() for r in rows)
        planned_util = (planned_total / (planned_makespan * n_m) * 100) if planned_makespan and n_m else 0.0
        actual_util = (actual_total / (actual_makespan * n_m) * 100) if actual_makespan and n_m else 0.0
        flow_source = actual_job_comp or planned_job_comp
        mean_flow = (sum(flow_source.values()) / len(flow_source)) if flow_source else 0.0
        dispatches = sum(1 for r in oht if r.get('event') == 'dispatch')

        planned_rows_html, _ = self._render_machine_rows(planned_by_m, machine_ids, mode='planned')
        actual_rows_html, _ = self._render_machine_rows(actual_by_m, machine_ids, mode='actual')

        ticks = ""
        for t in range(0, int(axis_makespan) + 1, 1800):
            ticks += (
                f'<div class="tick" style="left:{(t / axis_makespan * 100) if axis_makespan else 0.0:.3f}%">'
                f'<div class="tick-line"></div><span>{self._fmt(t)[:5]}</span></div>\n'
            )
        if planned_makespan > 0:
            ticks += (
                f'<div class="ms-line planned-line" style="left:{(planned_makespan / axis_makespan * 100) if axis_makespan else 0.0:.3f}%">'
                f'<span class="ms-tag">Plan {self._fmt(planned_makespan)}</span></div>\n'
            )
        if actual_makespan > 0:
            ticks += (
                f'<div class="ms-line actual-line" style="left:{(actual_makespan / axis_makespan * 100) if axis_makespan else 0.0:.3f}%">'
                f'<span class="ms-tag">Actual {self._fmt(actual_makespan)}</span></div>\n'
            )

        legend = (
            '<div class="leg-item">color = lot id (cycles through 15 colors)</div>\n'
            '<div class="leg-item">bar = machine processing (occupancy)</div>\n'
            '<div class="leg-item">gap between bars = machine idle / starvation (transport delay / buffer wait)</div>\n'
        )

        # many lots, so show only the top 40 with the latest completion times
        flow_keys = sorted(flow_source, key=lambda k: -flow_source[k])[:40]
        flow_html = ""
        for key in flow_keys:
            ct = flow_source[key]
            col = self.JOB_COLORS[(key - 1) % len(self.JOB_COLORS)] if key > 0 else self.JOB_COLORS[0]
            flow_html += (
                f'<div class="f-row"><span class="f-badge" style="background:{col}">L{key}</span>'
                f'<div class="f-track"><div class="f-bar" style="width:{(ct / axis_makespan * 100) if axis_makespan else 0.0:.3f}%;background:{col}"></div></div>'
                f'<span class="f-ct">{self._fmt(ct)}</span></div>\n'
            )

        oht_tbl = ""
        if oht:
            rows_html = ''.join(
                f'<tr><td>{r["sim_time"]}</td><td>OHT-{r["oht_id"]}</td>'
                f'<td>J{r["job_id"]}</td><td class="ev-{r["event"]}">{r["event"]}</td>'
                f'<td>{r["from_node"]}</td><td>{r["to_node"]}</td></tr>\n'
                for r in oht[:50]
            )
            oht_tbl = (
                f'<div class="sec"><div class="sec-title">OHT event log (latest 50 / {len(oht)} total)</div>'
                f'<div class="tbl-wrap"><table class="ev-tbl">'
                f'<thead><tr><th>sim_time</th><th>OHT</th><th>Job</th><th>event</th><th>from</th><th>to</th></tr></thead>'
                f'<tbody>{rows_html}</tbody></table></div></div>'
            )

        html = f'''<!DOCTYPE html>
<html lang="ko"><head><meta charset="UTF-8">
<title>Gantt - {os.path.basename(self.cfg.planned_gantt_csv)}</title>
<style>
*{{box-sizing:border-box;margin:0;padding:0}}
body{{font-family:system-ui,sans-serif;background:#1a1a2e;color:#e0e0e0;padding:20px;font-size:13px}}
h1{{font-size:17px;font-weight:500;color:#fff;margin-bottom:3px}}
.sub{{color:#666;font-size:11px;margin-bottom:14px}}
.metrics{{display:flex;gap:8px;flex-wrap:wrap;margin-bottom:14px}}
.card{{background:#16213e;border:0.5px solid #0f3460;border-radius:8px;padding:10px 14px;min-width:130px}}
.card .v{{font-size:20px;font-weight:500}}.card .l{{font-size:10px;color:#888;margin-top:2px}}
.card.green .v{{color:#4caf50}}.card.orange .v{{color:#ff9800}}.card.blue .v{{color:#42a5f5}}
.sec{{background:#16213e;border:0.5px solid #0f3460;border-radius:8px;padding:12px;margin-bottom:12px;overflow-x:auto}}
.sec-title{{font-size:11px;color:#888;font-weight:500;margin-bottom:8px}}
.legend{{display:flex;flex-wrap:wrap;gap:6px}}
.leg-item{{display:flex;align-items:center;gap:3px;font-size:10px;color:#aaa}}
.leg-dot{{width:10px;height:10px;border-radius:2px}}
.axis{{position:relative;height:22px;margin-left:44px;border-bottom:0.5px solid #333;margin-bottom:3px}}
.tick{{position:absolute;transform:translateX(-50%);display:flex;flex-direction:column;align-items:center;font-size:9px;color:#555;gap:2px}}
.tick-line{{width:1px;height:6px;background:#444}}
.ms-line{{position:absolute;top:0;bottom:0;width:1.5px;z-index:8}}
.planned-line{{background:#f59e0b}}
.actual-line{{background:#e94560}}
.ms-tag{{position:absolute;top:-16px;font-size:9px;transform:translateX(-50%);white-space:nowrap;background:#16213e;padding:0 2px}}
.g-row{{display:flex;align-items:center;height:22px;margin-bottom:2px}}
.g-lbl{{width:40px;font-size:10px;color:#666;text-align:right;padding-right:5px;flex-shrink:0}}
.g-track{{position:relative;flex:1;height:18px;background:#0d1b2a;border-radius:2px;overflow:hidden}}
.bar{{position:absolute;top:1px;height:16px;display:flex;align-items:center;justify-content:center;cursor:default}}
.bar:hover{{filter:brightness(1.15);z-index:5}}
.proc-bar{{border-radius:2px}}
.trans-bar{{border-radius:0 2px 2px 0}}
.bl{{font-size:8px;color:rgba(255,255,255,.9);font-weight:700;pointer-events:none;white-space:nowrap;overflow:hidden}}
.f-row{{display:flex;align-items:center;gap:6px;margin-bottom:4px}}
.f-badge{{width:36px;height:16px;border-radius:3px;font-size:9px;font-weight:700;color:#fff;display:flex;align-items:center;justify-content:center;flex-shrink:0}}
.f-track{{flex:1;height:12px;background:#0d1b2a;border-radius:2px;overflow:hidden}}
.f-bar{{height:100%;border-radius:2px;opacity:.85}}
.f-ct{{width:66px;font-size:10px;color:#666;text-align:right;flex-shrink:0}}
.tbl-wrap{{overflow-x:auto;max-height:280px;overflow-y:auto}}
.ev-tbl{{width:100%;border-collapse:collapse;font-size:11px}}
.ev-tbl th{{background:#0f3460;color:#aaa;padding:4px 8px;text-align:left;position:sticky;top:0}}
.ev-tbl td{{padding:3px 8px;border-bottom:0.5px solid #1a2744;color:#ccc}}
.ev-tbl tr:hover td{{background:#1e2d50}}
.ev-dispatch{{color:#4caf50;font-weight:500}}.ev-arrive{{color:#42a5f5;font-weight:500}}
.note{{font-size:10px;color:#8a96a3;line-height:1.45;margin-top:8px}}
</style></head><body>
<h1>Gantt Chart - {os.path.basename(self.cfg.planned_gantt_csv)}</h1>
<div class="sub">{n_j} lots x {n_m} machines | machine processing (occupancy) only · gap=starvation · planned (fixed plan) vs actual (realized) comparison</div>
<div class="metrics">
  <div class="card green"><div class="v">{self._fmt(planned_makespan)}</div><div class="l">Planned C_max</div></div>
  <div class="card orange"><div class="v">{self._fmt(actual_makespan)}</div><div class="l">Actual C_max</div></div>
  <div class="card blue"><div class="v">{planned_util:.1f}%</div><div class="l">Planned Utilization</div></div>
  <div class="card blue"><div class="v">{actual_util:.1f}%</div><div class="l">Actual Utilization</div></div>
  <div class="card"><div class="v">{dispatches}</div><div class="l">OHT Dispatches</div></div>
  <div class="card"><div class="v">{self._fmt(int(mean_flow))}</div><div class="l">Mean Flow Time</div></div>
</div>
<div class="sec"><div class="sec-title">Legend</div><div class="legend">{legend}</div>
</div>
<div class="sec">
  <div class="sec-title">Planned Machine Gantt</div>
  <div style="min-width:700px"><div class="axis">{ticks}</div><div>{planned_rows_html}</div></div>
</div>
<div class="sec">
  <div class="sec-title">Actual Machine Gantt</div>
  <div style="min-width:700px"><div class="axis">{ticks}</div><div>{actual_rows_html}</div></div>
</div>
<div class="sec"><div class="sec-title">Job Flow Time</div>{flow_html}</div>
{oht_tbl}
</body></html>'''

        out = self.cfg.gantt_html
        os.makedirs(os.path.dirname(os.path.abspath(out)) or '.', exist_ok=True)
        with open(out, 'w', encoding='utf-8') as f:
            f.write(html)
        print(f"  [HTML] gantt.html      → {out}")
        return out
